from acdg.tracks.data import TrackData

GEOMETRIES_TO_REMOVE = [
    "15_-_Default",
    "bbGrass",
    "marks",
    "tyres_add1",
    "tyres_add2",
    "Bark",
    "branch5",
    "it_pines",
    "IVY",
    "tree_shadow",
    "trees_new2",
    "trees_new2_AT",
]

MATERIAL_TO_SEMANTIC_CLASS = {
    "adv": "structure",
    "Asph-old": "road",
    "asph-pitlane": "road",
    # "Bark": "vegetation",
    # "branch5": "vegetation",
    "bridges": "structure",
    "buildings": "structure",
    "buildings-ablend": "structure",
    "buildings-AT": "structure",
    "cameraman": "people",
    "Curb-Shader": "carpet",
    "curb2": "curb",
    "driver_face": "people",
    "driver_suit": "people",
    "fences": "structure",
    "flag1": "structure",
    "flag2": "structure",
    "flag3": "structure",
    "flag4": "structure",
    "flag5": "structure",
    "flag6": "structure",
    "flag7": "structure",
    "flag8": "structure",
    "Gazebo_Tent": "structure",
    "Grass": "grass",
    "groove": "drivable",
    "Gstand": "structure",
    "Gstand_AT": "structure",
    "houses_add": "structure",
    "imola": "road",
    "imola_black_brd": "road",
    "imola_red_brd": "road",
    # "it_pines": "vegetation",
    # "IVY": "vegetation",
    "jersey": "structure",
    "kerb_NM": "curb",
    "marshalls": "people",
    "Material": "structure",
    "MB_Sprinter_2014": "vehicle",
    "metals": "structure",
    "Mobile_Shops": "vehicle",
    "numbers": "structure",
    "objects1": "structure",
    "Pannello_Skin_00": "structure",
    "peopleB": "people",
    "Pitlane_Props_BASE": "structure",
    "Sand": "grass",
    "Sand-16": "sand",
    "seatext": "grass",
    "spons-tower": "structure",
    "sponsors": "structure",
    "START_LIGHTS": "structure",
    "top1": "grass",
    "top1_MAP": "road",
    "top2": "grass",
    "tractor": "vehicle",
    # "tree_shadow": "vegetation",
    # "trees_new2": "vegetation",
    # "trees_new2_AT": "vegetation",
    "TV_Stuff": "vehicle",
    "Vehicles": "vehicle",
    "walls": "structure",
    "walls2": "structure",
}

VERTEX_GROUPS_TO_MODIFY = [
    "AC_AUDIO",
    "AC_PIIT",
    "AC_START",
    "AC_TIME",
]


IMOLA_DATA = TrackData(
    geometries_to_remove=GEOMETRIES_TO_REMOVE,
    vertex_groups_to_modify=VERTEX_GROUPS_TO_MODIFY,
    material_to_semantics=MATERIAL_TO_SEMANTIC_CLASS,
)
