FROM python:3.11.3-slim
# Update and install system packages
RUN apt-get update && apt-get install build-essential wget \
    gfortran libopenblas-dev pkg-config ffmpeg libsm6 libxext6 -y
# Install intel embree v2.17.7
RUN wget https://github.com/embree/embree/releases/download/v2.17.7/embree-2.17.7.x86_64.linux.tar.gz \
    -O /tmp/embree.tar.gz -nv && \
    tar -xzf /tmp/embree.tar.gz --strip-components=1 -C /usr/local && \
    rm -rf /tmp/embree.tar.gz
# Update pip    
RUN pip install --upgrade pip setuptools wheel
# Install pyembree
RUN pip install numpy cython
RUN pip install https://github.com/scopatz/pyembree/releases/download/0.1.6/pyembree-0.1.6.tar.gz
# Add intel embree to the path
ENV LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:/usr/local/lib"
# Install python packages
COPY requirements.txt .
RUN pip install -r requirements.txt
# Install ac-data-toolkit
COPY . .
RUN pip install -e .
# Run
ENV CONFIG_PATH "monza.yaml"
CMD python3 main.py ${CONFIG_PATH}