from src.tracks.data import TrackData

GEOMETRIES_TO_REMOVE = [
    "physics",
    "graffiti1",
    "graffiti2",
    "graffiti2_clean",
    "graffiti_clean",
    "graffiti4",
    "graffiti5",
    "bark",
    "bbgrass-b",
    "branch5",
    "Branches_03",
    "bushes1",
    "bushes2",
    "Material_#0",
    "park-bushb",
    "pines1",
    "pines_new",
    "tree2",
    "tree4",
    "tree5",
    "tree_shadow",
    "trees",
    "trees2",
    "trees_new",
    "treesline",
]

MATERIAL_TO_SEMANTIC_CLASS = {
    "groove": "drivable",
    "08_-_Default": "grass",
    "add": "structure",
    "adenau1": "structure",
    "adenau2": "structure",
    "adv": "structure",
    "advert": "structure",
    "ant1": "structure",
    "armco": "structure",
    "asph_ext": "road",
    "asph_ext_2": "road",
    "asph_green": "carpet",
    "asph_shad": "road",
    "asph_shad_dark": "road",
    "asphalt-": "road",
    "balloon": "vehicle",
    "barriers": "structure",
    "board_add": "carpet",
    "box": "structure",
    "box-alpha-spec": "structure",
    "brickfloor": "carpet",
    "brickfloor2": "carpet",
    "bridges": "structure",
    "brunnchen": "grass",
    "cables": "structure",
    "carpet": "carpet",
    "castle_D": "structure",
    "Chrome-TR": "structure",
    "concegrid": "carpet",
    "concrete": "road",
    "connection": "grass",
    "crk_long": "road",
    "curb": "structure",
    "curb-new": "curb",
    "curb_misc_new": "curb",
    "curbs": "curb",
    "display_park": "structure",
    "display_park_off": "structure",
    "driver_face": "people",
    "driver_suit": "people",
    "ED": "structure",
    "external": "structure",
    "fence": "structure",
    "fence-tile": "structure",
    "fence2-tile": "structure",
    "flag7": "structure",
    "flag8": "structure",
    "flag9": "structure",
    "glass-solid": "structure",
    "glass-transp": "structure",
    "grail-new": "structure",
    "grass": "grass",
    "grass_side_shad_3": "grass",
    "gravel-rd": "sand",
    "gravel_brd": "sand",
    "grass_brd": "grass",
    "gstands": "structure",
    "gstands-alpha": "structure",
    "gstands-alpha_blend": "structure",
    "hotel-old": "structure",
    "hyun": "structure",
    "jersey": "structure",
    "karussell": "road",
    "Kleinekarussel": "road",
    "km": "structure",
    "line_end": "road",
    "marsh-house": "structure",
    "marshall": "people",
    "MB_Sprinter_2014": "vehicle",
    "misc": "structure",
    "misc-alpha": "structure",
    "misc_add": "structure",
    "misc_AT": "structure",
    "names": "structure",
    "Nissan_Atlas_2007": "vehicle",
    "objects": "vehicle",
    "panel_aremberg1": "structure",
    "panel_aremberg2": "structure",
    "panel_new": "structure",
    "Pannello_Skin_00": "structure",
    "park-at": "structure",
    "park-dirt": "grass",
    "park-halt": "structure",
    "park-map": "structure",
    "park-roof": "structure",
    "park-sidewalk": "curb",
    "park-signasphalt": "road",
    "park-totem": "structure",
    "park1": "structure",
    "park_detail_8": "curb",
    "parkAO-shad": "structure",
    "parkAO-shad2": "structure",
    "pavement-brick": "road",
    "people_stand": "people",
    "peopleB": "people",
    "pitlane-alpha": "structure",
    "pitlane-alphaTS": "structure",
    "pitlane-multilayer": "structure",
    "pitlane-multimap": "structure",
    "pitlane-multimap2": "structure",
    "Pitlane_Props_BASE": "structure",
    "plankbase": "structure",
    "posiz": "road",
    "postaz-comm": "structure",
    "ppl": "people",
    "ring_parap": "structure",
    "sand": "sand",
    "sand_brd": "sand",
    "SAND_new": "sand",
    "sbanc_c": "grass",
    "scritte3": "structure",
    "semaphore": "structure",
    "semaphore_AT": "structure",
    "serraglio": "structure",
    "signs1": "structure",
    "Skoda_Octavia_Combi_2013": "vehicle",
    "structures": "structure",
    "t13": "structure",
    "t13-det": "structure",
    "tent": "structure",
    "tents": "structure",
    "tile_detail_5": "structure",
    "tile_detail_6": "road",
    "tile_detail_4": "road",
    "top2": "grass",
    "travr": "carpet",
    "trk-red": "vehicle",
    "trk-red-AB": "vehicle",
    "TV_Stuff": "vehicle",
    "tyres": "structure",
    "tyres_add": "structure",
    "tyres_add2": "structure",
    "Vehicles": "vehicle",
    "wall-t13": "road",
    "wall-t13_b": "structure",
    "wall1": "structure",
    "whiteline": "track_limit",
    "window_nw": "structure",
    # "bark": "vegetation",
    # "bbgrass-b": "vegetation",
    # "branch5": "vegetation",
    # "Branches_03": "vegetation",
    # "bushes1": "vegetation",
    # "bushes2": "vegetation",
    # "Material_#0": "vegetation",
    # "park-bushb": "vegetation",
    # "pines1": "vegetation",
    # "pines_new": "vegetation",
    # "tree2": "vegetation",
    # "tree4": "vegetation",
    # "tree5": "vegetation",
    # "tree_shadow": "vegetation",
    # "trees": "vegetation",
    # "trees2": "vegetation",
    # "trees_new": "vegetation",
    # "treesline": "vegetation",
}

VERTEX_GROUPS_TO_MODIFY = [
    "AC_AUDIO",
    "AC_PIT",
    "AC_POBJECT",
    "AC_START",
    "AC_TIME",
    "AC_HOTLAP_START",
]


NORDSCHLEIFE_DATA = TrackData(
    geometries_to_remove=GEOMETRIES_TO_REMOVE,
    vertex_groups_to_modify=VERTEX_GROUPS_TO_MODIFY,
    material_to_semantics=MATERIAL_TO_SEMANTIC_CLASS,
)
