from src.tracks.data import TrackData

GEOMETRIES_TO_REMOVE = [
    "physics",
    "trees",
    "Leaves",
    "Bark",
    "tree_shadow",
    "horizont",
    "bbgrass",
]

MATERIAL_TO_SEMANTIC_CLASS = {
    "matt_big_source": "drivable",
    # "trees": "vegetation",
    "MB_Sprinter_2014": "vehicle",
    "structures": "structure",
    "misc": "structure",
    "bridges": "structure",
    "barriers1": "structure",
    "box1": "structure",
    "box1_multimap": "structure",
    "gstands1": "structure",
    "box2": "structure",
    "tile1": "structure",
    "objects1": "vehicle",
    "metals1": "structure",
    "tile1B": "structure",
    "fences1": "structure",
    "flag5": "structure",
    "flag1b": "structure",
    "flag1": "structure",
    "flag2": "structure",
    "flag3": "structure",
    "flag4": "structure",
    "flag5": "structure",
    "grass": "grass",
    "asphalt": "road",
    "sand_new": "sand",
    "Curb_new": "curb",
    "curb": "curb",
    "sand-bordini": "grass",
    "stone": "structure",
    "box2": "structure",
    "glass_transp": "structure",
    "ADV_add": "structure",
    "marshall": "people",
    "grass_paint": "grass",
    "top2": "grass",
    "asph_pitlane": "road",
    "glass": "structure",
    "glass_transp": "structure",
    "miscalpha": "structure",
    "walls2": "structure",
    "bridge": "structure",
    "grass_NM": "structure",
    "top2_NM": "grass",
    "top2_refl": "grass",
    "peopleB": "people",
    "grass_brd": "grass",
    # "Bark": "vegetation",
    # "Leaves": "vegetation",
    # "tree_shadow": "vegetation",
    "tyreswall": "structure",
}

VERTEX_GROUPS_TO_MODIFY = [
    "AC_AUDIO",
    "AC_PIT",
    "AC_POBJECT",
    "AC_START",
    "AC_TIME",
    "AC_HOTLAP_START",
]


SILVERSTONE_DATA = TrackData(
    geometries_to_remove=GEOMETRIES_TO_REMOVE,
    vertex_groups_to_modify=VERTEX_GROUPS_TO_MODIFY,
    material_to_semantics=MATERIAL_TO_SEMANTIC_CLASS,
)
