from src.tracks.data import TrackData

GEOMETRIES_TO_REMOVE = [
    "groove1",
    "groove2",
    "groove3",
    "trees2B",
    "treesline",
    "trees1",
    "bbgrassb",
    "bushesB",
    "bushes",
    "trees2",
    "bbgrass",
    "physics",
    "top-ext",
]

MATERIAL_TO_SEMANTIC_CLASS = {
    "houses3": "structure",
    "Glass": "structure",
    "walls": "structure",
    "metals1": "structure",
    "Vehicles": "vehicle",
    "houses13": "structure",
    "box1-ppix": "structure",
    # "bushes": "vegetation",
    # "trees2": "vegetation",
    "texts_new": "structure",
    "Glass-blend": "structure",
    "grass-side1B": "grass",
    "water": "water",
    "grass-side2": "grass",
    "line": "track_limit",
    "box1_map": "structure",
    "new_AO2": "structure",
    "new_AO": "structure",
    "diss": "curb",
    "sbancamento_D": "structure",
    "sand_new": "sand",
    "box-door": "structure",
    "grass-side1": "grass",
    "fence-special": "structure",
    "glasswall": "structure",
    "jersey": "structure",
    "kerb_new": "curb",
    "grilles": "curb",
    "barriers": "structure",
    "grass-side4": "grass",
    "box-door2": "structure",
    "grails": "structure",
    "misc": "structure",
    "objects1": "vehicle",
    "marshall": "people",
    "hedge": "vegetation",
    "house7_Slot_#1": "structure",
    "fences": "structure",
    "stones_detail1": "structure",
    "box1_multimap": "structure",
    "Concrete": "structure",
    "asph_pitlane_old": "road",
    "seat1": "structure",
    "houses5": "structure",
    "texts": "structure",
    "parking": "road",
    "houses11": "structure",
    "houses10": "structure",
    "houses9": "structure",
    "houses12": "structure",
    "old-gstand1": "structure",
    "old-gstand2": "structure",
    "old-box1": "structure",
    "old-box2": "structure",
    "houses8": "structure",
    "box1": "structure",
    "main-gstand": "structure",
    "houses7": "structure",
    "houses6": "structure",
    "houses4": "structure",
    "houses2": "structure",
    "houses1": "structure",
    "asph-grv": "road",
    "GRASS": "grass",
    "sand": "sand",
    "carpet": "carpet",
    "grass-ext-shad": "grass",
    "asph-pitlane-old": "road",
    "asph": "road",
    "CURB_B": "curb",
    "road-ext-tile": "road",
    "flag7": "structure",
    "flag8": "structure",
    # "trees2B": "vegetation",
    # "treesline": "vegetation",
    # "trees1": "vegetation",
    # "bbgrassb": "vegetation",
    # "bushesB": " vegetation",
    "fence2_at": "structure",
    "grille-alpha_test": "structure",
    "transp-alpha_test": "structure",
    # "bbgrass": "vegetation",
    "driver_suit": "people",
    "Pannello_Skin_00": "structure",
    "Pitlane_Props_BASE": "structure",
    "driver_face": "people",
}

VERTEX_GROUPS_TO_MODIFY = [
    "AC_PIT",
    "AC_START",
    "AC_HOTLAP_START",
]


SPA_DATA = TrackData(
    geometries_to_remove=GEOMETRIES_TO_REMOVE,
    vertex_groups_to_modify=VERTEX_GROUPS_TO_MODIFY,
    material_to_semantics=MATERIAL_TO_SEMANTIC_CLASS,
)
