from src.tracks.data import TrackData

GEOMETRIES_TO_REMOVE = [
    "scratch",
    "bushes.001",
    "Bark",
    "pine",
    "trees_new",
    "tree_shadow",
    "leaves",
    "bbgrass",
    "horizont",
    "polys",
    "physics",
]

MATERIAL_TO_SEMANTIC_CLASS = {
    "top_refl": "grass",
    "wall-gstand": "structure",
    "box-window": "structure",
    "glasses": "structure",
    "palo": "structure",
    "bridge01": "structure",
    "metal": "structure",
    "cgs_b": "structure",
    "cgs": "structure",
    "sand_new.001": "sand",
    "field1": "structure",
    "curb_new": "curb",
    "jersey": " structure",
    "cgs-glass": "structure",
    "walls.001": "structure",
    "tv_staff": "structure",
    "Gazebo_Tent": "structure",
    "Vehicles.001": "vehicle",
    "tractor": "vehicle",
    "MB_Sprinter_2014": "vehicle",
    "Pitlane_Props_BASE": "structure",
    "metals": "structure",
    "box1b": "structure",
    "curbtext2b": "curb",
    "Material_#25": "structure",
    "curbtext2c": "curb",
    "curb_new2": " curb",
    "wall02": "structure",
    "wall03": "structure",
    "tyres_add": "structure",
    "bricks_wall": "structure",
    "Gas_Station": "structure",
    "flags9": "structure",
    "adenau1": "structure",
    "shops": "structure",
    "camera": "structure",
    "marshall.001": "person",
    "Pannello_Skin_00.001": "structure",
    "object1.001": "structure",
    "external2": "grass",
    "box_alphablend": "structure",
    "box1.001": "structure",
    "dist": "structure",
    "numbers": "structure",
    "sponsors1": "structure",
    "bb1": "structure",
    "riga": "track_limit",
    "ashpalt-new": "road",
    "boxenterance1": "structure",
    "01_-_Default": "structure",
    "stee_light": "structure",
    "boxenterance2": "structure",
    "tyres3": "structure",
    "fence": "structure",
    "field222": "grass",
    "misc2": "structure",
    "curb-mult-shader": "curb",
    "curb-mult2-shader": "curb",
    "top": "grass",
    "ashpalt_new": "road",
    "tarmac-box": "road",
    "tarmac3": "road",
    "grass": "grass",
    "grass-sand": "sand",
    "flag8": "structure",
    "flag7": "structure",
    "structures_alpha": "structure",
    "people": "people",
    "box_alpha": "structure",
    "gstand1": "structure",
    "gstand1-alpha": "structure",
    "brd2": "sand",
    "driver_suit": "people",
    "driver_face": "people",
}

VERTEX_GROUPS_TO_MODIFY = [
    "AC_PIT",
    "AC_HOTLAP_START",
    "AC_START",
]


VALLELUNGA_DATA = TrackData(
    geometries_to_remove=GEOMETRIES_TO_REMOVE,
    vertex_groups_to_modify=VERTEX_GROUPS_TO_MODIFY,
    material_to_semantics=MATERIAL_TO_SEMANTIC_CLASS,
)
