track_mesh_path: /tracks/imola/modified_imola.obj
recorded_data_path: /data/recordings/imola/audi_r8_lms_2016/sillybois
output_path: /out/imola/audi_r8_lms_2016/sillybois
track_name: imola
car_name: audi_r8_lms_2016
start_at_sample: 0
finish_at_sample: -1
sample_every: 3
vertical_fov: 60
image_size: [1600, 900]
n_ray_casting_workers: 3
n_generation_workers: 2
generate:
  segmentation:
    - data
    - visuals
    # - overlays
  #depth:
  #  - visuals
  #normals:
  #  - visuals