track_mesh_path: /mnt/tracks/monza/modified_monza.obj
recorded_data_path: /mnt/monza_audi_r8_lms_1/
output_path: /mnt/generated/
track_name: monza
car_name: audi_r8_lms_2016
start_at_sample: 450
finish_at_sample: -1
sample_every: 1
vertical_fov: 60
image_size: [1920, 1080]
n_ray_casting_workers: 6
n_generation_workers: 4
generate:
  segmentation:
    - data
    - visuals
    # - overlays
  depth:
    - visuals
  normals:
    - visuals