track_mesh_path: /tracks/monza/modified_monza.obj
recorded_data_path: /data/monza/audi_r8_lms_2016/fastbois
output_path: /out/monza/audi_r8_lms_2016/fastbois
track_name: monza
car_name: audi_r8_lms_2016
start_at_sample: 0
finish_at_sample: -1
sample_every: 3
vertical_fov: 60
image_size: [1600, 900]
n_ray_casting_workers: 1
n_generation_workers: 1
generate:
  segmentation:
    - data
    - visuals
    # - overlays
  #depth:
  #  - visuals
  #normals:
  #  - visuals