track_mesh_path: /tracks/ks_nordschleife/nordschleife_modified.obj
recorded_data_path: /data/recordings_v3/nordschleife/audi_r8_lms_2016/sillybois
output_path: /out/nordschleife/audi_r8_lms_2016/sillybois
track_name: nordschleife
car_name: audi_r8_lms_2016
start_at_sample: 0
finish_at_sample: -1
sample_every: 3
vertical_fov: 60
image_size: [1280, 736]
n_ray_casting_workers: 2
n_generation_workers: 1
generate:
  segmentation:
    - data
    - visuals
    # - overlays
  #depth:
  #  - visuals
  #normals:
  #  - visuals