track_mesh_path: /tracks/ks_vallelunga/modified_vallelunga.obj
recorded_data_path: /data/vallelunga/audi_r8_lms_2016/sillybois
output_path: /out/vallelunga/audi_r8_lms_2016/test/
track_name: vallelunga
car_name: audi_r8_lms_2016
start_at_sample: 0
finish_at_sample: -1
sample_every: 10
vertical_fov: 60
image_size: [1600, 900]
n_ray_casting_workers: 2
n_generation_workers: 1
generate:
  segmentation:
    - data
    - visuals
  #  - overlays
  #depth:
  #  - visuals
  #normals:
  #  - visuals