track_mesh_path: /tracks/abudhabi_euroracers_v2/yas_marina_modified.obj
recorded_data_path: /data/recordings_v3/yas_marina/audi_r8_lms_2016/trying_fast_bois
output_path: /out/yas_marina/audi_r8_lms_2016/trying_fast_bois
track_name: yas_marina
car_name: audi_r8_lms_2016
start_at_sample: 0
finish_at_sample: -1
sample_every: 3
vertical_fov: 60
image_size: [1600, 900]
n_ray_casting_workers: 3
n_generation_workers: 2
generate:
  segmentation:
    - data
    - visuals
    # - overlays
  #depth:
  #  - visuals
  #normals:
  #  - visuals